yarnPath: .yarn/releases/yarn-3.0.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

logFilters:
  # Ignore "can't be found in the cache and will be fetched from the remote registry"
  - code: YN0013
    level: discard
