version: '3'
services:
  speedtest:
    container_name: speedtest
    image: joelvaneenwyk/docker-speedtest-analyser
    restart: unless-stopped
    #network_mode: bridge
    volumes:
      - ./data:/var/www/html/data
    ports:
      - 8080:80
      - 4343:443
    environment:
      - CRONJOB_ITERATION=15
