version: '3'
services:
  speedtest:
    build: .
    container_name: speedtest
    image: joelvaneenwyk/docker-speedtest-analyser
    restart: unless-stopped
    volumes:
      - ./data:/var/www/html/data
    ports:
      - 11010:80
      - 11011:443
    environment:
      - CRONJOB_ITERATION=15
