version: "3.7"
services:
    speedtest:
        build: .
        container_name: speedtest_analyzer
        image: joelvaneenwyk/speedtest-analyzer
        restart: unless-stopped
        volumes:
            - ./html/data/:/usr/share/nginx/html/data/
        ports:
            - 15010:80
            - 15011:443
        environment:
            - CRONJOB_ITERATION=15
